### ISSUE TITLE
Колаборация с официальным переводом

### ISSUE THREAD

**Issue by gaearon** [stsiushkevich/learn-reactjs#105]
Мы начали официальный перевод здесь: https://github.com/reactjs/ru.reactjs.org/issues/1.

Кто-то оставил ссылку на эту версию. Вопрос — есть ли у вас желание сотрудничать? Мы были бы рады, если бы вы присоединились и/или разрешили использовать ваши тексты в процессе перевода где имеет смысл.

Если вы против, это тоже ок — просто было бы здорово узнать точно. ) Спасибо!

**Comment by lex111** [comment]
сс @stsiushkevich

**Comment by stsiushkevich** [comment]
Здравствуйте! Неожиданно приятно, что вы написали мне. Ситуация интересная получается, мы дублируем одну информацию в двух местах. Я не против, конечно, если вы будете без переусердства использовать мой контент - но он не соответствует вашим правилам перевода((. Возможно присоединюсь к переводу, если будет время и желание. Спасибо!

**Comment by stsiushkevich** [comment]
Простите за критику, но слово "пропсы" - режет мне глаза)) Нет такого слова в русском языке - оно англоид. Я бы всёже оставил "свойства". Оно используется в веб докумментациях уже давно. А вообще я к вам зашел почитать правила перевода и подумал, что мне нужно улучшить свой собственный, большое спасибо за подсказку.

**Comment by stsiushkevich** [comment]
Ой, совсем забыл, а вы расширяете свою команду? (у меня мечта)

**Comment by lex111** [comment]
> Возможно присоединюсь к переводу, если будет время и желание.
> Ситуация интересная получается, мы дублируем одну информацию в двух местах.
> Ой, совсем забыл, а вы расширяете свою команду? (у меня мечта)

Вот поэтому мы написали, чтобы был только один единый перевод. Поскольку у вас наиболее полный, а следовательно наиболее используемый в рунете, то было хорошо, когда работа над переводом завершится, то, скажем, помочь мигрировать пользователей на официальный перевод.

> Я бы всёже оставил "свойства".

У нас было обсуждение [этого](https://github.com/reactjs/ru.reactjs.org/issues/4#issuecomment-461990965).

> Нет такого слова в русском языке

Я тоже так думал, но в реальности мы уже употребляем [много](https://github.com/web-standards-ru/dictionary/blob/master/dictionary.md) нерусских слов, это в данном случае разумный компромисс: так много говорят, это наиболее верно передаёт суть (да, просто транслитерация).

**Comment by stsiushkevich** [comment]
> помочь мигрировать пользователей на официальный перевод

Мне не составит труда разместить у себя ссылку на ваш сайт. У меня тематика шире. Я планирую добавлять разделы Create React App и, возможно какие-то другие. Будет не только сам React, но и сопутсвующие библиотеки, рецепты и так далее.

**Comment by lex111** [comment]
Проблема только в том, что будут существовать два альтернативных перевода, вы же ведь и дальше планируете поддерживать в актуальном состоянии собственный перевод? Тогда смысл в этом?

**Comment by stsiushkevich** [comment]
> Проблема только в том, что будут существовать два альтернативных перевода, вы же ведь и дальше планируете поддерживать в актуальном состоянии собственный перевод? Тогда смысл в этом?

Смысл в том, что вашего проекта раньше не было. Я был первый. Также я разместил рекламу, чтобы возмещать потраченное время. Раскрутил сайт, потратив свои деньги. И вы предлогаете весь мой трафик подарить вам?))) Я никак не мешаю вашему проекту.

**Comment by lex111** [comment]
Подожите, может это неочевидно, либо я не понимаю, но это не _мой_ личный проект, это проект как раз сообщества. Поэтому предлагалось объединиться, чтобы иметь единый (лучший, если хотите) перевод, который будет создаваться и поддерживаться силами сообщества. В качестве примера можно привести неофициальный китайский перевод, который [мигрировал](https://github.com/discountry/react/commit/ca5e57fe8069438589b0bc6f488bc55c5d617179) в репозиторий официального сообщества React. 
Ваша позиция понятна: вы планируете поддерживать свой проект. Без проблем, хорошо, можно было ограничиться этим простым ответом, а не писать что-то вроде:

> Разница ещё и в том, что я заинтересован в качестве перевода, обладая большим опытом разработки и перевода.

**Comment by gaearon** [comment]
Кажется, мы начали не с той ноги. )

Сергей, мы очень ценим ваши усилия. Ваша работа помогла сделать React популярным в России, и за это вам большое спасибо.

Понятно, что это лично ваш проект, и если он вам помогает материально, то вам не имеет смысла участвовать в другом переводе. Особенно если вы с какими-то вопросами несогласны, или если ваша цель покрыть много проектов в одном месте. Это всё понятно.

Я хотел немножко прояснить вопрос с нашей стороны. Мы не собираемся заимствовать ваши переводы, если вам самому это некомфортно. Пока что мы пишем с нуля. Ваш опыт перевода помог бы — но мы постараемся и так справиться. Конечно, где-то будет хуже.

С другой стороны, мы не хотим быть официальной «плохой документацией». Мы ценим русский язык (https://github.com/reactjs/ru.reactjs.org/pull/6). Конечно, мы не опытные переводчики, и помощь в редактировании была бы кстати.

Про термины типа «пропсы» и «рендеринг» я вас прекрасно понимаю. Мы стараемся избегать их, но некоторые трудно избежать по техническим причинам (русские варианты дают неправильные ассоциации). Где нет таких проблем, мы стараемся переводить (например, «задержка», а не Suspense; «предохранитель», а не “error boundary”). Если вы хотите поучаствовать в переводе, но строго несогласны с каким-то термином, вы можете создать тему, и мы с удовольствием обсудим эти решения (и, возможно, изменим их). Нам важно качество и живой язык.

Наш перевод будет официальным, поэтому для многих он будет первым в любом случае. Если вы поможете, он может получиться лучше. Но если вы предпочитаете продолжать работу независимо и не участвовать, мы тоже это понимаем и не будем больше вас беспокоить. 

Спасибо!

**Comment by stsiushkevich** [comment]
Я уверен, что усилиями сообщества, к которому я себя тоже отношу, **перевод получится ничем не хуже моего**. Но так сложилось, что я с большим энтузиазмом вложился материально и по времени, чтобы дать возможность тем, кто плохо знает английский, тоже в полной мере освоить ваш шедевр. Ведь я сам когда-то начинал и ничего нигде не было на русском. Посетители благодарны мне за ресурс, поэтому я не хочу просто так убивать мое детище)).

Сам же я буду с интересом наблюдать за развитием вашего ресурса и постараться не быть безучастным. Как-никак я хочу внести свой след в распространение React))

Спасибо за ваше понимание, Денис!

**Comment by Fly-Style** [comment]
@stsiushkevich Он Даниил :)
