### ISSUE TITLE
Опечатка: исправить "кокой-то" на "какой-то"

### ISSUE THREAD

**Issue by geek10010** [stsiushkevich/learn-reactjs#109]
Здравствуйте, Сергей!
Спасибо за Вашу инициативу по переводу!
Я обнаружил опечатку: в файле [https://github.com/stsiushkevich/learn-reactjs/blob/c40749e0df02f0f0eb65053c6fa04395aa75758a/src/main/webapp/WEB-INF/tags/application/introduction/add-react-to-web-site/code-example-1.tag](https://github.com/stsiushkevich/learn-reactjs/blob/c40749e0df02f0f0eb65053c6fa04395aa75758a/src/main/webapp/WEB-INF/tags/application/introduction/add-react-to-web-site/code-example-1.tag) нужно исправить "кокой-то" на "какой-то".

**Comment by stsiushkevich** [comment]
> Здравствуйте, Сергей!
> Спасибо за Вашу инициативу по переводу!
> Я обнаружил опечатку: в файле https://github.com/stsiushkevich/learn-reactjs/blob/c40749e0df02f0f0eb65053c6fa04395aa75758a/src/main/webapp/WEB-INF/tags/application/introduction/add-react-to-web-site/code-example-1.tag нужно исправить "кокой-то" на "какой-то".

Спасибо! Поправлю)

**Comment by JustMonk** [comment]
#112
