### ISSUE TITLE
Пример не понятный без контекста

### ISSUE THREAD

**Issue by bscheshirwork** [stsiushkevich/learn-reactjs#133]
https://reactjs.org/docs/handling-events.html#passing-arguments-to-event-handlers

нет блока
```
В случае использования инициализатора свойств, можно использовать и такой вариант:
 <button onClick={this.deleteRow}>Delete Row</button>
Данный вариант эквивалентен варианту с bind и имеет самую короткую и читабельную форму записи, но для его корректной работы вам нужно использовать Babel.
```

И не ясно как же он работает. Где параметр, который передаётся? Как выглядит объявление/реализация обработчика deleteRow?

**Comment by stsiushkevich** [comment]
Здравствуйте! Большое спасибо за ваше замечание. Действительно - ничего не понятно:) Исправим.
