### ISSUE TITLE
Hide content paddings in mobile version

### ISSUE THREAD

**Issue by ArturGodunov** [stsiushkevich/learn-reactjs#59]
Привет. Было бы круто убрать боковые отступы в контенте на маленьких разрешениях. На смартфоне значительно удобнее становится читать.
Можно как-то так:
@media (max-width: 480px) {
  .content--mobile {
    padding-left: 0;
    padding-right: 0;
  }
  .disqus-thread--mobile {
    padding-left: 15px;
    padding-right: 15px;
  }
}

**Comment by stsiushkevich** [comment]
Здравствуйте! Хорошо, я постараюсь сделать удобнее.

**Comment by stsiushkevich** [comment]
Готово!

**Comment by ArturGodunov** [comment]
Круть! Смотрится отлично!
